name: Build APK artifact

on:
  push:
    branches-ignore:
      - master
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the code
        uses: actions/checkout@v7

      - name: Setup java environment
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: temurin

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v6

      - name: Build fdroid debug APK
        run: ./gradlew assembleFdroidDebug

      - name: Upload APK
        uses: actions/upload-artifact@v7
        with:
          name: currencies-fdroid-debug-${{ github.sha }}
          path: app/build/outputs/apk/fdroid/debug/*.apk
          if-no-files-found: error
